# --- 锚点定义 (通用属性) ---
proxy_providers_common:
  &p {
    type: http,
    interval: 86400,
    proxy: DIRECT,
    health-check:
      {
        enable: true,
        url: https://g.cn/generate_204,
        interval: 600,
        lazy: true,
      },
  }

# 全局过滤节点
exclude:
  &exclude {
    exclude-filter: '群|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|超时|收藏|福利|邀请|好友|失联|选择|剩余|公益|发布|DIZTNA|通路|登录|禁止|定时|渠道|牢记|永久|余额|阁下|本站|刷新|导航|⚠️|@|Expire|http|com',
  }

# 订阅提供者，如果你想要添加多个订阅提供者，可以复制 provider1 的配置块，并修改 url 和 path 字段。
proxy-providers:
  provider1:
    <<: [*p, *exclude]
    url: '此处填入机场订阅链接'
    path: ./proxy_providers/provider1.yaml
#  provider2:
#   <<: [*p, *exclude]
#   url: '此处填入机场订阅链接'
#   path: ./proxy_providers/provider2.yaml

# --- 基础全局配置 ---

allow-lan: true
ipv6: true
bind-address: '*'
unified-delay: true
tcp-concurrent: true
keep-alive-idle: 600
keep-alive-interval: 60
find-process-mode: strict
external-controller: '[::]:9090'
external-ui: ui
external-ui-url: 'https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip'

profile:
  store-selected: true
  store-fake-ip: true

# 直连节点
proxies:
  - { name: '🇨🇳 直连 | IPv4优先', type: direct, ip-version: ipv4-prefer }
  - { name: '🇨🇳 直连 | IPv6优先', type: direct, ip-version: ipv6-prefer }
  - { name: '🇨🇳 直连 | 双栈', type: direct }

# 国内外 DNS 定义
chinaDNS:
  &chinaDNS [
    'https://dns.alidns.com/dns-query#DIRECT',
    'https://doh.pub/dns-query#DIRECT',
  ]
foreignDNS:
  &foreignDNS [
    'https://1.1.1.1/dns-query#默认代理',
    'https://8.8.8.8/dns-query#默认代理',
  ]

dns:
  enable: true
  ipv6: true
  listen: :1053
  cache-algorithm: arc
  use-hosts: true
  use-system-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range-v6: 'fc00::/18'
  fake-ip-filter:
    - 'rule-set:private'
    - 'rule-set:fakeip_filter'
  proxy-server-nameserver: *chinaDNS
  default-nameserver:
    - '223.5.5.5'
    - '119.29.29.29'
  nameserver: *foreignDNS
  nameserver-policy:
    '*': 'system'
    'rule-set:cn': *chinaDNS
  direct-nameserver: [system]

hosts:
  'dns.alidns.com': ['223.5.5.5', '223.6.6.6']
  'doh.pub': ['1.12.12.12', '120.53.53.53']

  # 解决谷歌商店无法下载的问题
  'services.googleapis.cn': ['services.googleapis.com']

  # 屏蔽哔哩哔哩PCDN，解决访问视频卡顿问题
  '+.mcdn.bilivideo.com': ['0.0.0.0']
  '+.mcdn.bilivideo.cn': ['0.0.0.0']

ntp:
  enable: true
  write-to-system: false
  server: 'ntp.aliyun.com'
  port: 123
  interval: 60

tun:
  enable: true
  stack: system
  auto-route: true
  strict-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack: ['udp://any:53', 'tcp://any:53']

# --- 规则集 ---

# Rule Provider 通用配置
rule_providers_common:
  rp_domain: &rp_domain { type: http, interval: 86400, behavior: domain }
  rp_ip: &rp_ip { type: http, interval: 86400, behavior: ipcidr }
  rp_classical:
    &rp_classical { type: http, interval: 86400, behavior: classical }

# 定义 Rule Providers
rule-providers:
  adblockmihomolite:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/217heidai/adblockfilters@main/rules/adblockmihomolite.mrs'
    path: './ruleset/adblockmihomolite.mrs'
  DownloadApps:
    <<: *rp_classical
    format: text
    url: 'https://fastly.jsdelivr.net/gh/AIsouler/MyClash@main/Rules/DownloadApps.txt'
    path: './ruleset/DownloadApps.txt'
  fakeip_filter:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/wwqgtxx/clash-rules@release/fakeip-filter.mrs'
    path: './ruleset/fakeip-filter.mrs'
  epicgames:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/epicgames.mrs'
    path: './ruleset/epicgames.mrs'
  nvidia_cn:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/nvidia@cn.mrs'
    path: './ruleset/nvidia@cn.mrs'
  ai:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ai-!cn.mrs'
    path: './ruleset/ai.mrs'
  youtube:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/youtube.mrs'
    path: './ruleset/youtube.mrs'
  googlefcm:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/googlefcm.mrs'
    path: './ruleset/googlefcm.mrs'
  google:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google.mrs'
    path: './ruleset/google.mrs'
  google_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/google.mrs'
    path: './ruleset/google_ip.mrs'
  github:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/github.mrs'
    path: './ruleset/github.mrs'
  microsoft:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft.mrs'
    path: './ruleset/microsoft.mrs'
  microsoft_cn:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft@cn.mrs'
    path: './ruleset/microsoft@cn.mrs'
  telegram:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.mrs'
    path: './ruleset/telegram.mrs'
  telegram_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/telegram.mrs'
    path: './ruleset/telegram_ip.mrs'
  pixiv:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/pixiv.mrs'
    path: './ruleset/pixiv.mrs'
  steam:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/steam.mrs'
    path: './ruleset/steam.mrs'
  games_cn:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-games@cn.mrs'
    path: './ruleset/category-games@cn.mrs'
  twitter:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/twitter.mrs'
    path: './ruleset/twitter.mrs'
  twitter_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/twitter.mrs'
    path: './ruleset/twitter_ip.mrs'
  private:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs'
    path: './ruleset/private.mrs'
  private_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs'
    path: './ruleset/private_ip.mrs'
  gfw:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/gfw.mrs'
    path: './ruleset/gfw.mrs'
  cn_additional:
    <<: *rp_domain
    format: mrs
    url: 'https://static-file-global.353355.xyz/rules/cn-additional-list.mrs'
    path: './ruleset/cn-additional-list.mrs'
  cn:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/wwqgtxx/clash-rules@release/direct.mrs'
    path: './ruleset/cn.mrs'
  cn_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs'
    path: './ruleset/cn_ip.mrs'
  emby:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/666OS/rules@release/mihomo/domain/Emby.mrs'
    path: './ruleset/emby.mrs'
  emby_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/666OS/rules@release/mihomo/ip/Emby.mrs'
    path: './ruleset/emby_ip.mrs'
  spotify:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/spotify.mrs'
    path: './ruleset/spotify.mrs'
  tiktok:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/tiktok.mrs'
    path: './ruleset/tiktok.mrs'
  netflix:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/netflix.mrs'
    path: './ruleset/netflix.mrs'
  netflix_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/netflix.mrs'
    path: './ruleset/netflix_ip.mrs'
  cloudflare:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cloudflare.mrs'
    path: './ruleset/cloudflare.mrs'
  cloudflare_cn:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cloudflare@cn.mrs'
    path: './ruleset/cloudflare@cn.mrs'
  cloudflare_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cloudflare.mrs'
    path: './ruleset/cloudflare_ip.mrs'
  apple:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/apple.mrs'
    path: './ruleset/apple.mrs'
  apple_cn:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/apple@cn.mrs'
    path: './ruleset/apple@cn.mrs'
  instagram:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/instagram.mrs'
    path: './ruleset/instagram.mrs'

# --- 策略组 (Proxy Groups) ---

# 策略组通用配置
group_common_select:
  &group_common_select {
    type: select,
    interval: 600,
    timeout: 3000,
    max-failed-times: 3,
    url: 'https://g.cn/generate_204',
    lazy: true,
  }

group_common_auto:
  &group_common_auto {
    type: url-test,
    interval: 600,
    timeout: 3000,
    max-failed-times: 3,
    url: 'https://g.cn/generate_204',
    lazy: true,
    tolerance: 100,
    include-all: true,
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png',
    hidden: true,
  }

# 通用代理节点组
prox_common:
  &proxies {
    proxies:
      [
        '默认代理',
        '香港',
        '日本',
        '美国',
        '新加坡',
        '台湾省',
        '低倍率节点',
        '高倍率节点',
        '其他节点',
      ],
  }

# 定义分流策略组
proxy-groups:
  - name: '默认代理'
    <<: *group_common_select
    proxies:
      [
        '香港',
        '日本',
        '美国',
        '新加坡',
        '台湾省',
        '低倍率节点',
        '高倍率节点',
        '其他节点',
      ]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png'

  - name: 'AI'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/ChatGPT.png'

  - name: 'YouTube'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png'

  - name: 'FCM'
    <<: *group_common_select
    proxies:
      [
        '直连',
        '默认代理',
        '香港',
        '日本',
        '美国',
        '新加坡',
        '台湾省',
        '低倍率节点',
        '高倍率节点',
        '其他节点',
      ]
    icon: 'https://fastly.jsdelivr.net/gh/MiToverG422/Qure@master/IconSet/Color/fcm.png'

  - name: 'Google'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png'

  - name: 'GitHub'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png'

  - name: 'Microsoft'
    <<: *group_common_select
    proxies:
      [
        '默认代理',
        '直连',
        '香港',
        '日本',
        '美国',
        '新加坡',
        '台湾省',
        '低倍率节点',
        '高倍率节点',
        '其他节点',
      ]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png'

  - name: 'Apple'
    <<: *group_common_select
    proxies:
      [
        '默认代理',
        '直连',
        '香港',
        '日本',
        '美国',
        '新加坡',
        '台湾省',
        '低倍率节点',
        '高倍率节点',
        '其他节点',
      ]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png'

  - name: 'Telegram'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png'

  - name: 'Cloudflare'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png'

  - name: 'Pixiv'
    <<: [*group_common_select, *proxies]
    icon: 'https://play-lh.googleusercontent.com/Ls9opXo6-wfEWmbBU8heJaFS8HwWydssWE1J3vexIGvkF-UJDqcW7ZMD8w6dQABfygONd4z3Yt4TfRDZAPYq=w480-h960-rw'

  - name: 'Steam'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png'

  - name: 'Twitter'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png'

  - name: 'Instagram'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Instagram.png'

  - name: 'Emby'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Emby.png'

  - name: 'Spotify'
    <<: *group_common_select
    proxies:
      [
        '默认代理',
        '直连',
        '香港',
        '日本',
        '美国',
        '新加坡',
        '台湾省',
        '低倍率节点',
        '高倍率节点',
        '其他节点',
      ]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png'

  - name: 'TikTok'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png'

  - name: 'Netflix'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png'

  - name: '广告拦截'
    <<: *group_common_select
    proxies: ['REJECT', 'REJECT-DROP', 'PASS']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Advertising.png'

  - name: '直连'
    <<: *group_common_select
    proxies: ['🇨🇳 直连 | IPv4优先', '🇨🇳 直连 | IPv6优先', '🇨🇳 直连 | 双栈']
    url: 'https://connectivitycheck.platform.hicloud.com/generate_204'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/China_Map.png'

  # 定义地区策略组
  - name: '香港'
    <<: *group_common_select
    include-all: true
    proxies: ['香港-自动选择']
    filter: '🇭🇰|港|HK|[Hh]ong\s*[Kk]ong'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png'
  - name: '香港-自动选择'
    <<: *group_common_auto
    filter: '🇭🇰|港|HK|[Hh]ong\s*[Kk]ong'

  - name: '日本'
    <<: *group_common_select
    include-all: true
    proxies: ['日本-自动选择']
    filter: '🇯🇵|日本|JP|[Jj]apan'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png'
  - name: '日本-自动选择'
    <<: *group_common_auto
    filter: '🇯🇵|日本|JP|[Jj]apan'

  - name: '美国'
    <<: *group_common_select
    include-all: true
    proxies: ['美国-自动选择']
    filter: '🇺🇸|美|US|[Aa]merica|[Uu]nited\s*[Ss]tates'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png'
  - name: '美国-自动选择'
    <<: *group_common_auto
    filter: '🇺🇸|美|US|[Aa]merica|[Uu]nited\s*[Ss]tates'

  - name: '新加坡'
    <<: *group_common_select
    include-all: true
    proxies: ['新加坡-自动选择']
    filter: '🇸🇬|新加坡|狮城|SG|[Ss]ingapore'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png'
  - name: '新加坡-自动选择'
    <<: *group_common_auto
    filter: '🇸🇬|新加坡|狮城|SG|[Ss]ingapore'

  - name: '台湾省'
    <<: *group_common_select
    include-all: true
    proxies: ['台湾省-自动选择']
    filter: '🇹🇼|台湾|TW|[Tt]aiwan'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png'
  - name: '台湾省-自动选择'
    <<: *group_common_auto
    filter: '🇹🇼|台湾|TW|[Tt]aiwan'

  - name: '低倍率节点'
    <<: *group_common_select
    include-all: true
    filter: '^(?!.*(?:剩|期|客户端|软件)).*(?:(?<!\d)0\.[0-5]|下载|低倍)'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available_1.png'

  - name: '高倍率节点'
    <<: *group_common_select
    include-all: true
    filter: '(?u)(?:[*×xX✕✖⨉]\s*(?:[2-9]\d*|[1-9]\d+)(?:\.\d+)?)|(?:(?<![\d.])(?:[2-9]\d*|[1-9]\d+)(?:\.\d+)?\s*(?:倍|[*×xX✕✖⨉]))'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Airport.png'

  - name: '其他节点'
    <<: *group_common_select
    include-all: true
    proxies: ['其他节点-自动选择']
    exclude-filter: '港|HK|🇭🇰|日本|JP|🇯🇵|美|US|🇺🇸|新加坡|SG|🇸🇬|台湾|TW|🇹🇼|直连'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/World_Map.png'
  - name: '其他节点-自动选择'
    <<: *group_common_auto
    exclude-filter: '港|HK|🇭🇰|日本|JP|🇯🇵|美|US|🇺🇸|新加坡|SG|🇸🇬|台湾|TW|🇹🇼|直连'

# --- 路由规则 (Rules) ---
rules:
  # 私有网络直连
  - RULE-SET,private,直连
  - RULE-SET,private_ip,直连,no-resolve

  # 国内直连
  - RULE-SET,games_cn,直连
  - RULE-SET,epicgames,直连
  - RULE-SET,nvidia_cn,直连
  - RULE-SET,microsoft_cn,直连
  - RULE-SET,cloudflare_cn,直连
  - RULE-SET,apple_cn,直连
  - DOMAIN,fsend.cn,直连

  # 进程规则
  - RULE-SET,DownloadApps,直连 # 常见磁力下载软件
  - PROCESS-NAME,com.perol.pixez,Pixiv
  - PROCESS-NAME,com.perol.play.pixez,Pixiv

  # 广告拦截
  - RULE-SET,adblockmihomolite,广告拦截

  # 阻断 YouTube UDP 流量
  - AND,((NETWORK,UDP),(DST-PORT,443),(RULE-SET,youtube)),REJECT

  # 代理规则（域名）
  - RULE-SET,ai,AI
  - RULE-SET,youtube,YouTube
  - RULE-SET,googlefcm,FCM
  - RULE-SET,google,Google
  - RULE-SET,github,GitHub
  - RULE-SET,microsoft,Microsoft
  - RULE-SET,apple,Apple
  - RULE-SET,telegram,Telegram
  - RULE-SET,cloudflare,Cloudflare
  - RULE-SET,pixiv,Pixiv
  - RULE-SET,steam,Steam
  - RULE-SET,twitter,Twitter
  - RULE-SET,instagram,Instagram
  - RULE-SET,emby,Emby
  - DOMAIN-KEYWORD,emby,Emby
  - RULE-SET,spotify,Spotify
  - RULE-SET,tiktok,TikTok
  - RULE-SET,netflix,Netflix

  # 代理规则（IP）
  - RULE-SET,google_ip,Google,no-resolve
  - RULE-SET,telegram_ip,Telegram,no-resolve
  - RULE-SET,twitter_ip,Twitter,no-resolve
  - RULE-SET,cloudflare_ip,Cloudflare,no-resolve
  - RULE-SET,emby_ip,Emby,no-resolve
  - RULE-SET,netflix_ip,Netflix,no-resolve

  # 兜底规则
  - RULE-SET,gfw,默认代理
  - RULE-SET,cn_additional,直连
  - RULE-SET,cn_ip,直连
  - MATCH,默认代理
